//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForMeeting.SharedKernel.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ForMeeting.SharedKernel.Recursos.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O autor é obrigatório..
        /// </summary>
        public static string AssociadoObrigatorio {
            get {
                return ResourceManager.GetString("AssociadoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da categoria dever possuir de {0} à {1} caracteres..
        /// </summary>
        public static string CategoriaNomeLimiteDeCaracteres {
            get {
                return ResourceManager.GetString("CategoriaNomeLimiteDeCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da categoria é obrigatório..
        /// </summary>
        public static string CategoriaNomeObrigatorio {
            get {
                return ResourceManager.GetString("CategoriaNomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da cidade dever possuir de {0} à {1} caracteres..
        /// </summary>
        public static string CidadeNomeLimiteDeCaracteres {
            get {
                return ResourceManager.GetString("CidadeNomeLimiteDeCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da cidade é obrigatório..
        /// </summary>
        public static string CidadeNomeObrigatorio {
            get {
                return ResourceManager.GetString("CidadeNomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comentário inválido..
        /// </summary>
        public static string ComentarioInvalido {
            get {
                return ResourceManager.GetString("ComentarioInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cpf inválido..
        /// </summary>
        public static string CpfInvalido {
            get {
                return ResourceManager.GetString("CpfInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este CPF já se encontra cadastrado à um cliente no sistema..
        /// </summary>
        public static string CpfJaCadastrado {
            get {
                return ResourceManager.GetString("CpfJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF é obrigatório..
        /// </summary>
        public static string CpfObrigatorio {
            get {
                return ResourceManager.GetString("CpfObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato da Data de Nascimento é inválido..
        /// </summary>
        public static string DataDeNascimentoFormatacaoInvalida {
            get {
                return ResourceManager.GetString("DataDeNascimentoFormatacaoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento inválido. Usuário deve ser maior de idade..
        /// </summary>
        public static string DataDeNascimentoInvalida {
            get {
                return ResourceManager.GetString("DataDeNascimentoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail inválido..
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este E-mail já se encontra cadastrado à um cliente no sistema..
        /// </summary>
        public static string EmailJaCadastrado {
            get {
                return ResourceManager.GetString("EmailJaCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail é obrigatório..
        /// </summary>
        public static string EmailObrigatorio {
            get {
                return ResourceManager.GetString("EmailObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do estado dever possuir de {0} à {1} caracteres..
        /// </summary>
        public static string EstadoNomeLimiteDeCaracteres {
            get {
                return ResourceManager.GetString("EstadoNomeLimiteDeCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do estado é obrigatório..
        /// </summary>
        public static string EstadoNomeObrigatorio {
            get {
                return ResourceManager.GetString("EstadoNomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado é obrigatório..
        /// </summary>
        public static string EstadoObrigatorio {
            get {
                return ResourceManager.GetString("EstadoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla do estado dever possuir de {0} à {1} caracteres..
        /// </summary>
        public static string EstadoSiglaLimiteDeCaracteres {
            get {
                return ResourceManager.GetString("EstadoSiglaLimiteDeCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla do estado é obrigatório..
        /// </summary>
        public static string EstadoSiglaObrigatorio {
            get {
                return ResourceManager.GetString("EstadoSiglaObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário/Autor do evento é obrigatório..
        /// </summary>
        public static string EventoCriadorObrigatorio {
            get {
                return ResourceManager.GetString("EventoCriadorObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do evento dever possuir de {0} à {1}  caracteres..
        /// </summary>
        public static string EventoDescricaoLimiteDeCaracteres {
            get {
                return ResourceManager.GetString("EventoDescricaoLimiteDeCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição do evento é obrigatório..
        /// </summary>
        public static string EventoDescricaoObrigatorio {
            get {
                return ResourceManager.GetString("EventoDescricaoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localização do evento é obrigatória..
        /// </summary>
        public static string EventoLocalidadeObrigatorio {
            get {
                return ResourceManager.GetString("EventoLocalidadeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O evento é obrigatório..
        /// </summary>
        public static string EventoObrigatorio {
            get {
                return ResourceManager.GetString("EventoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título do evento dever possuir de {0} à {1} caracteres..
        /// </summary>
        public static string EventoTituloLimiteDeCaracteres {
            get {
                return ResourceManager.GetString("EventoTituloLimiteDeCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título do evento é obrigatório..
        /// </summary>
        public static string EventoTituloObrigatorio {
            get {
                return ResourceManager.GetString("EventoTituloObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro da localidade é obrigatório..
        /// </summary>
        public static string LocalidadeBairroObrigatorio {
            get {
                return ResourceManager.GetString("LocalidadeBairroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP da localidade inválido..
        /// </summary>
        public static string LocalidadeCepInvalido {
            get {
                return ResourceManager.GetString("LocalidadeCepInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade da localidade é obrigatório..
        /// </summary>
        public static string LocalidadeCidadeObrigatorio {
            get {
                return ResourceManager.GetString("LocalidadeCidadeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado da localidade dever possuir no máximo de 2 caracteres..
        /// </summary>
        public static string LocalidadeEstadoMaximoTresCaracteres {
            get {
                return ResourceManager.GetString("LocalidadeEstadoMaximoTresCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado da localidade é obrigatório..
        /// </summary>
        public static string LocalidadeEstadoObrigatorio {
            get {
                return ResourceManager.GetString("LocalidadeEstadoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro da localidade é obrigatório..
        /// </summary>
        public static string LocalidadeLogradouroObrigatorio {
            get {
                return ResourceManager.GetString("LocalidadeLogradouroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da localidade dever possuir de {0} à {1} caracteres..
        /// </summary>
        public static string LocalidadeNomeLimiteDeCaracteres {
            get {
                return ResourceManager.GetString("LocalidadeNomeLimiteDeCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da localidade é obrigatório..
        /// </summary>
        public static string LocalidadeNomeObrigatorio {
            get {
                return ResourceManager.GetString("LocalidadeNomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número da localidade é obrigatório..
        /// </summary>
        public static string LocalidadeNumeroObrigatorio {
            get {
                return ResourceManager.GetString("LocalidadeNumeroObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo da localidade dever possuir de {0} à {1} caracteres..
        /// </summary>
        public static string LocalidadeTipoLimiteDeCaracteres {
            get {
                return ResourceManager.GetString("LocalidadeTipoLimiteDeCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo da localidade é obrigatório..
        /// </summary>
        public static string LocalidadeTipoObrigatorio {
            get {
                return ResourceManager.GetString("LocalidadeTipoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máximo de {0} caracteres..
        /// </summary>
        public static string MaximoCaracteres {
            get {
                return ResourceManager.GetString("MaximoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimo de {2} caracteres no campo {0}..
        /// </summary>
        public static string MinimoCaracteres {
            get {
                return ResourceManager.GetString("MinimoCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome inválido..
        /// </summary>
        public static string NomeInvalido {
            get {
                return ResourceManager.GetString("NomeInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O nome é obrigatório..
        /// </summary>
        public static string NomeObrigatorio {
            get {
                return ResourceManager.GetString("NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do país dever possuir de {0} à {1} caracteres..
        /// </summary>
        public static string PaisNomeLimiteDeCaracteres {
            get {
                return ResourceManager.GetString("PaisNomeLimiteDeCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do país é obrigatório..
        /// </summary>
        public static string PaisNomeObrigatorio {
            get {
                return ResourceManager.GetString("PaisNomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País é obrigatório..
        /// </summary>
        public static string PaisObrigatorio {
            get {
                return ResourceManager.GetString("PaisObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigla do país dever possuir de {0} à {1} caracteres..
        /// </summary>
        public static string PaisSiglaLimiteDeCaracteres {
            get {
                return ResourceManager.GetString("PaisSiglaLimiteDeCaracteres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Senha não compativel com Senha..
        /// </summary>
        public static string SenhasNaoCompativeis {
            get {
                return ResourceManager.GetString("SenhasNaoCompativeis", resourceCulture);
            }
        }
    }
}
